### ISSUE TITLE
Thread problems with Fragments

### ISSUE THREAD

**Issue by ahornerr** [codebutler/android-websockets#5]
I know this has more to do with Koush's Socket.IO fork but I feel like it may apply to both.
I've posted the issue on SO and I feel like I explained it fairly well; Basically whenever I try to disconnect a socket inside a fragment, I get an error from the Looper.

http://stackoverflow.com/questions/14362387/android-socket-io-with-fragments

I'm more than happy to include any more information as this is really starting to drive me crazy trying to find a solution.

Thanks!

**Comment by codebutler** [comment]
There's no indication that this problem has anything to do with my code.
